### ISSUE TITLE
 File "main.py", line 3, in <module>     from google import google

### ISSUE THREAD

**Issue by SubhashKsr** [vyraun/Google-Search-Chatbot#1]
Followed the following steps, as mentioned in ReadMe

## Installation

1. Clone and navigate to chatbot directory.

2. Install modules.
    ```bash
    pip install Flask
    pip install Google-Search-API
    ```

3. Run the python server.
    ```bash
    python main.py

After this step, I am seeing the following error, tried surfing a little about that but couldnt fix it. Please help me out.

[ksr@ksr-PC: ~/Documents/Google-Search-Chatbot-master ] python main.py 
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from google import google
ImportError: cannot import name google

**Comment by Daniel-code-lang** [comment]
ok

**Comment by griditalianet** [comment]
pip install googlesearch-python

from flask import Flask, render_template, request, jsonify
from googlesearch import search

app = Flask(__name__)

@app.route("/")
def hello():
    return render_template('chat.html')

@app.route("/ask", methods=['POST'])
def ask():
    message = str(request.form['messageText'])

    # kernel now ready for use
    while True:
        if message == "quit":
            exit()
        else:
            search_results = search(message, num_results=2)
            if len(search_results) > 1:
                bot_response = search_results[1]
            else:
                bot_response = "Mi dispiace, non ho trovato informazioni sulla tua richiesta."
            print(bot_response)
            # return bot_response
            return jsonify({'status': 'OK', 'answer': bot_response})

if __name__ == "__main__":
    app.run(debug=True)

**Comment by griditalianet** [comment]
c'e molto da fare
